files:
  - source: /po/com.github.rafostar.Clapper.pot
    translation: /po/%osx_locale%.po
    languages_mapping:
      osx_locale:
        zh-Hant: zh_TW
        zh-Hans: zh_CN
        sv: sv_SE
        pt: pt_PT
        es: es_ES
