files:
  - source: /src/lib/clapper-gtk/po/clapper-gtk.pot
    translation: /src/lib/clapper-gtk/po/%osx_locale%.po
  - source: /src/bin/clapper-app/po/clapper-app.pot
    translation: /src/bin/clapper-app/po/%osx_locale%.po
