on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: "Flatpak"
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: "Build"
      with:
        bundle: com.github.rafostar.Clapper.flatpak
        manifest-path: pkgs/flatpak/com.github.rafostar.Clapper.json
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}
