on:
  schedule:
    - cron: "0 0 * * *"
name: "Flatpak Nightly"
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: "Build"
      with:
        bundle: com.github.rafostar.Clapper.flatpak
        manifest-path: pkgs/flatpak/com.github.rafostar.Clapper-testing.json
        cache-key: flatpak-builder-${{ github.sha }}-testing-${{ github.run_number }}
